import { execFile } from "child_process";
import { promisify } from "util";
import { writeFile, readFile, rm, mkdir } from "fs/promises";
import { tmpdir } from "os";
import { join } from "path";

const execFileAsync = promisify(execFile);

/**
 * Convert HTML content to PDF using LaTeX (pdflatex).
 * Requires `pdflatex` installed on the system.
 * Falls back gracefully if not available.
 */
export async function generateWithLatex(
  html: string,
  template: string,
  _markdown?: string
): Promise<Buffer> {
  // Check if pdflatex is available
  try {
    await execFileAsync("pdflatex", ["--version"]);
  } catch {
    throw new Error("pdflatex not found on system PATH");
  }

  const workDir = join(tmpdir(), `doccraft-${Date.now()}`);
  await mkdir(workDir, { recursive: true });

  const texFile = join(workDir, "document.tex");
  const pdfFile = join(workDir, "document.pdf");

  try {
    // Convert HTML to LaTeX
    const latex = htmlToLatex(html, template);
    await writeFile(texFile, latex, "utf8");

    // Run pdflatex (twice for proper TOC/cross-references)
    const args = [
      "-interaction=nonstopmode",
      "-output-directory",
      workDir,
      texFile,
    ];

    await execFileAsync("pdflatex", args, { cwd: workDir });
    await execFileAsync("pdflatex", args, { cwd: workDir }); // Second pass

    const pdfBuffer = await readFile(pdfFile);
    return pdfBuffer;
  } finally {
    await rm(workDir, { recursive: true, force: true });
  }
}

function fontPackageForTemplate(template: string): string {
  switch (template) {
    case "professional":
    case "compliance":
      return "\\usepackage{palatino}\n\\usepackage{mathpazo}";
    case "document":
      return "\\usepackage{lmodern}";
    case "saas":
    case "modern":
    default:
      return "\\usepackage{helvet}\n\\renewcommand{\\familydefault}{\\sfdefault}";
  }
}

function htmlToLatex(html: string, template: string): string {
  // Strip HTML tags to get plain text content (simplified for MVP)
  const text = html
    .replace(/<h1[^>]*>(.*?)<\/h1>/gi, "\\section*{$1}\n")
    .replace(/<h2[^>]*>(.*?)<\/h2>/gi, "\\subsection*{$1}\n")
    .replace(/<h3[^>]*>(.*?)<\/h3>/gi, "\\subsubsection*{$1}\n")
    .replace(/<strong>(.*?)<\/strong>/gi, "\\textbf{$1}")
    .replace(/<em>(.*?)<\/em>/gi, "\\textit{$1}")
    .replace(/<code>(.*?)<\/code>/gi, "\\texttt{$1}")
    .replace(/<pre><code[^>]*>([\s\S]*?)<\/code><\/pre>/gi, (_, code) => {
      return `\\begin{verbatim}\n${unescapeHtml(code)}\n\\end{verbatim}`;
    })
    .replace(/<blockquote>(.*?)<\/blockquote>/gi, "\\begin{quote}$1\\end{quote}\n")
    .replace(/<ul>([\s\S]*?)<\/ul>/gi, (_, items) => {
      const lis = items.replace(/<li>(.*?)<\/li>/gi, "  \\item $1\n");
      return `\\begin{itemize}\n${lis}\\end{itemize}\n`;
    })
    .replace(/<ol>([\s\S]*?)<\/ol>/gi, (_, items) => {
      const lis = items.replace(/<li>(.*?)<\/li>/gi, "  \\item $1\n");
      return `\\begin{enumerate}\n${lis}\\end{enumerate}\n`;
    })
    .replace(/<p>(.*?)<\/p>/gi, "$1\n\n")
    .replace(/<a[^>]*href="([^"]*)"[^>]*>(.*?)<\/a>/gi, "$2 (\\url{$1})")
    .replace(/<[^>]+>/g, "") // strip remaining tags
    .replace(/&amp;/g, "\\&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/#/g, "\\#")
    .replace(/%/g, "\\%")
    .replace(/\$/g, "\\$")
    .replace(/_/g, "\\_")
    .replace(/\^/g, "\\^{}")
    .replace(/~/g, "\\~{}");

  const fontPackage = fontPackageForTemplate(template);

  return `\\documentclass[12pt,a4paper]{article}
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage[margin=2.5cm]{geometry}
\\usepackage{hyperref}
\\usepackage{url}
\\usepackage{verbatim}
\\usepackage{parskip}
\\usepackage{xcolor}
${fontPackage}
\\definecolor{accentcolor}{RGB}{192,101,26}
\\hypersetup{colorlinks=true,linkcolor=accentcolor,urlcolor=accentcolor}
\\setlength{\\parindent}{0pt}
\\setlength{\\parskip}{8pt}

\\begin{document}
\\thispagestyle{empty}

${text}

\\vfill
\\begin{center}
  \\small\\textcolor{gray}{Generated by DocCraft}
\\end{center}

\\end{document}
`;
}

function unescapeHtml(str: string): string {
  return str
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"');
}
